services:
  - type: web
    name: himss-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn analysis:main() -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 